//! A repository-owned Rust fixture exercises a declared command through the
//! actual CLI. It has no dependencies, build script or network need; Cargo is
//! forced offline. The project is in scratch space, and both settings and store
//! are outside it. This measures completion, which a pre-cancelled runner cannot.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};

const SURE: &str = env!("CARGO_BIN_EXE_sure");

fn write(path: &Path, text: &str) {
    std::fs::write(path, text)
        .unwrap_or_else(|error| panic!("could not write {}: {error}", path.display()));
}

fn fixture() -> (PathBuf, PathBuf, PathBuf, PathBuf) {
    let root = sure_testkit::scratch::directory("finished declared check é中文", "rust fixture");
    let project = root.join("project with spaces");
    let store = root.join("store");
    std::fs::create_dir_all(&project).expect("project directory");
    std::fs::create_dir_all(&store).expect("store directory");
    write(
        &project.join("Cargo.toml"),
        "[package]\nname = 'sure_fixture'\nversion = '0.1.0'\nedition = '2021'\n\
         [lib]\npath = 'lib.rs'\n\n[workspace]\n",
    );
    // Pre-existing lockfile keeps Cargo from changing the fingerprint during
    // the check. A new lockfile would correctly make an earlier result stale.
    write(
        &project.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\nversion = 4\n\n\
         [[package]]\nname = \"sure_fixture\"\nversion = \"0.1.0\"\n",
    );
    let marker = root.join("test actually executed.txt");
    write(
        &project.join("lib.rs"),
        &format!(
            "#[cfg(test)]\nmod tests {{ #[test] fn works() {{ \
             std::fs::write({:?}, b\"the declared test ran\").unwrap(); \
             assert_eq!(2 + 2, 4); }} }}\n",
            marker.to_string_lossy()
        ),
    );
    let settings = root.join("user-settings.yaml");
    write(&settings, "execution:\n  mode: inspect_only\n");
    (project, store, settings, marker)
}

fn check(project: &Path, store: &Path, settings: &Path, format: &str) -> Output {
    Command::new(SURE)
        .arg("--store-dir")
        .arg(store)
        .arg("--settings-file")
        .arg(settings)
        .args(["--format", format, "check"])
        .arg(project)
        .env("CARGO_NET_OFFLINE", "true")
        .env_remove("CARGO_TARGET_DIR")
        .stdin(Stdio::null())
        .output()
        .expect("the CLI starts")
}

#[test]
fn a_declared_check_finishes_and_its_result_reaches_both_cli_reports() {
    let (project, store, settings, marker) = fixture();
    assert!(!marker.exists(), "the fixture's test has not run yet");
    let denied = check(&project, &store, &settings, "json");
    let denied_frame: serde_json::Value =
        serde_json::from_slice(&denied.stdout).expect("the denied run produced a JSON frame");
    let denied_rows = denied_frame["details"]["check_results"]
        .as_array()
        .expect("the denied run has check rows");
    assert!(
        denied_rows
            .iter()
            .any(|row| row["title"] == "run the tests" && row["status"] == "skipped"),
        "the default mode did not refuse the declared test: {denied_frame}"
    );
    assert!(!marker.exists(), "inspect_only ran the project's test");

    write(
        &settings,
        "execution:\n  mode: host_confirmed\n  allow_network: true\n",
    );
    let output = check(&project, &store, &settings, "json");
    let stdout = String::from_utf8(output.stdout).expect("the JSON report is UTF-8");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.code().is_some(),
        "the CLI did not finish normally: {stdout}\n{stderr}"
    );
    assert_eq!(
        std::fs::read(&marker).expect("the declared test wrote its marker"),
        b"the declared test ran"
    );
    let frame: serde_json::Value = serde_json::from_str(&stdout).expect("one JSON frame");
    assert_eq!(frame["details"]["state"], "finished");
    assert_eq!(
        frame["details"]["grants"]["execution_mode"],
        "host_confirmed"
    );
    assert_eq!(frame["details"]["report"]["totals"]["could_not_run"], 0);
    let rows = frame["details"]["check_results"]
        .as_array()
        .expect("the CLI carries the run's explicit check rows");
    let tests: Vec<_> = rows
        .iter()
        .filter(|row| row["title"] == "run the tests")
        .collect();
    assert_eq!(
        tests.len(),
        1,
        "one result for this declared check: {rows:?}"
    );
    assert_eq!(tests[0]["status"], "pass", "{tests:?}");
    assert_eq!(tests[0]["critical"], true);
    assert_ne!(tests[0]["project_fingerprint"], serde_json::Value::Null);
    assert!(
        !frame["details"]["report"]["not_checked"]
            .as_array()
            .expect("the verdict lists gaps")
            .iter()
            .any(|row| row["title"] == "run the tests"),
        "a completed check was also reported as unrun: {frame}"
    );

    let human = check(&project, &store, &settings, "human");
    let human_stdout = String::from_utf8(human.stdout).expect("human report is UTF-8");
    assert!(
        human.status.code().is_some(),
        "the human report did not finish normally: {human_stdout}\n{}",
        String::from_utf8_lossy(&human.stderr)
    );
    assert!(
        human_stdout.contains("Checks that passed"),
        "{human_stdout}"
    );
    assert!(
        human_stdout.contains("pass: run the tests"),
        "{human_stdout}"
    );
}
